# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='cat',
            name='kitten',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cat',
            name='father',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='male',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mother',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='litter',
            name='title',
            field=models.CharField(max_length=2),
        ),
    ]
