# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0002_auto_20160417_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='status',
            field=models.CharField(default='Свободен', max_length=20),
        ),
    ]
