# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0003_cat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
